server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=2

            - id: employee-service-route
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/v1/employees/**
              filters:
                - StripPrefix=2 # strip the uri two slash (remove the /api/v1 ) before routing the request
                - JwtValidation # Spring will look for a class that is prefixed with 'GatewayFilterFactory'

            - id: attendance-service-route
              uri: lb://ATTENDANCE-SERVICE
              predicates:
                - Path=/api/v1/attendance/**
              filters:
                - StripPrefix=2
                - JwtValidation

            - id: payroll-service-route
              uri: lb://PAYROLL-SERVICE
              predicates:
                - Path=/api/v1/payroll/**
              filters:
                - StripPrefix=2
                - JwtValidation

            - id: performance-review-service-route
              uri: lb://PERFORMANCE-REVIEW-SERVICE
              predicates:
                - Path=/api/v1/performance-reviews/**
              filters:
                - StripPrefix=2
                - JwtValidation

# Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

# Auth Service URL
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:4005}
